--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/11/2022 3:00:38 PM
-- Server version: 10.2.41
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE ntstore;

--
-- Drop table `export_invoice_product`
--
DROP TABLE IF EXISTS export_invoice_product;

--
-- Drop table `export_invoice`
--
DROP TABLE IF EXISTS export_invoice;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Drop table `import_invoice_product`
--
DROP TABLE IF EXISTS import_invoice_product;

--
-- Drop table `import_invoice`
--
DROP TABLE IF EXISTS import_invoice;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop table `category`
--
DROP TABLE IF EXISTS category;

--
-- Drop table `manufacture`
--
DROP TABLE IF EXISTS manufacture;

--
-- Set default database
--
USE ntstore;

--
-- Create table `manufacture`
--
CREATE TABLE manufacture (
  ManufactureID int(11) NOT NULL AUTO_INCREMENT,
  ManufactureName varchar(255) DEFAULT NULL,
  Address varchar(255) DEFAULT NULL,
  PhoneNumber varchar(100) DEFAULT NULL,
  PRIMARY KEY (ManufactureID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'Nhà cung c?p';

--
-- Create table `category`
--
CREATE TABLE category (
  CategoryID int(11) NOT NULL AUTO_INCREMENT,
  CategoryName varchar(255) DEFAULT NULL,
  PRIMARY KEY (CategoryID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'danh m?c';

--
-- Create table `product`
--
CREATE TABLE product (
  ProductID int(11) NOT NULL AUTO_INCREMENT,
  ProductName varchar(255) DEFAULT NULL,
  ExportPrice double DEFAULT NULL,
  ImportPrice double DEFAULT NULL,
  CategoryID int(11) DEFAULT NULL,
  Description varchar(255) DEFAULT NULL,
  Quality int(11) DEFAULT NULL,
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'S?n ph?m';

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT FK_product_CategoryID FOREIGN KEY (CategoryID)
REFERENCES category (CategoryID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID int(11) NOT NULL AUTO_INCREMENT,
  EmployeeCode varchar(100) DEFAULT NULL,
  `Position` varchar(255) DEFAULT NULL,
  AccoutName varchar(255) DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'Nhân viên';

--
-- Create table `import_invoice`
--
CREATE TABLE import_invoice (
  InvoiceID int(11) NOT NULL AUTO_INCREMENT,
  InvoiceName varchar(255) DEFAULT NULL,
  DateCreate date DEFAULT NULL,
  EmployeeID int(11) DEFAULT NULL,
  ManufactureID int(11) DEFAULT NULL,
  PRIMARY KEY (InvoiceID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'Hóa don nh?p';

--
-- Create foreign key
--
ALTER TABLE import_invoice
ADD CONSTRAINT FK_import_invoice_EmployeeID FOREIGN KEY (EmployeeID)
REFERENCES employee (EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE import_invoice
ADD CONSTRAINT FK_import_invoice_ManufactureID FOREIGN KEY (ManufactureID)
REFERENCES manufacture (ManufactureID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `import_invoice_product`
--
CREATE TABLE import_invoice_product (
  InvoiceID int(11) NOT NULL,
  ProductID int(11) NOT NULL,
  TotalImport int(11) DEFAULT NULL,
  PriceImport double DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'Hóa don nh?p s?n ph?m';

--
-- Create foreign key
--
ALTER TABLE import_invoice_product
ADD CONSTRAINT FK_import_invoice_product_InvoiceID FOREIGN KEY (InvoiceID)
REFERENCES import_invoice (InvoiceID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE import_invoice_product
ADD CONSTRAINT FK_import_invoice_product_ProductID FOREIGN KEY (ProductID)
REFERENCES product (ProductID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `customer`
--
CREATE TABLE customer (
  CustomerID int(11) NOT NULL AUTO_INCREMENT,
  CustomerCode varchar(100) DEFAULT NULL,
  Address varchar(255) DEFAULT NULL,
  PhoneNumber varchar(100) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  Gender int(11) DEFAULT NULL,
  DateOfBirth datetime DEFAULT NULL,
  CustomerName varchar(255) DEFAULT NULL,
  PRIMARY KEY (CustomerID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 60,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'B?ng khách hàng';

--
-- Create table `export_invoice`
--
CREATE TABLE export_invoice (
  InvoiceID int(11) NOT NULL AUTO_INCREMENT,
  InvoiceName varchar(255) DEFAULT NULL,
  DateCreate date DEFAULT NULL,
  CustomerID int(11) DEFAULT NULL,
  EmployeeID int(11) DEFAULT NULL,
  PRIMARY KEY (InvoiceID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'hóa don xuát';

--
-- Create foreign key
--
ALTER TABLE export_invoice
ADD CONSTRAINT FK_export_invoice_CustomerID FOREIGN KEY (CustomerID)
REFERENCES customer (CustomerID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE export_invoice
ADD CONSTRAINT FK_export_invoice_EmployeeID FOREIGN KEY (EmployeeID)
REFERENCES employee (EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `export_invoice_product`
--
CREATE TABLE export_invoice_product (
  InvoiceID int(11) DEFAULT NULL,
  ProductID int(11) DEFAULT NULL,
  TotalExport int(11) DEFAULT NULL,
  PriceExport double DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci,
COMMENT = 'Hóa don xu?t - s?n ph?m';

--
-- Create foreign key
--
ALTER TABLE export_invoice_product
ADD CONSTRAINT FK_export_invoice_product_InvoiceID FOREIGN KEY (InvoiceID)
REFERENCES export_invoice (InvoiceID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE export_invoice_product
ADD CONSTRAINT FK_export_invoice_product_ProductID FOREIGN KEY (ProductID)
REFERENCES product (ProductID) ON DELETE CASCADE ON UPDATE CASCADE;

-- 
-- Dumping data for table manufacture
--
-- Table ntstore.manufacture does not contain any data (it is empty)

-- 
-- Dumping data for table category
--
-- Table ntstore.category does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table ntstore.employee does not contain any data (it is empty)

-- 
-- Dumping data for table customer
--
INSERT INTO customer VALUES
(11, 'KH01', 'B?c Giang', '0337966780', '2001Hoang@gmail.com', 0, '2001-10-10 00:00:00', 'Nguyen Quoc Yen'),
(57, 'kh011', 'lghsgkdsfg', '0333354539654', '2001tambh@gmail.com', 0, '2022-04-07 00:00:00', 'Nguyen VÄƒn Mi'),
(58, 'kh10', 'HÃ  Ná»™i', '0333354539654', '2001tambh@gmail.com', 0, '2022-04-20 00:00:00', 'Nguyen VÄƒn Mi'),
(59, 'kh011', 'YÃªn BÃ¡i', '0333354539654', '2001tambh@gmail.com', 0, '2022-04-20 00:00:00', 'Nguyen VÄƒn Mi');

-- 
-- Dumping data for table import_invoice
--
-- Table ntstore.import_invoice does not contain any data (it is empty)

-- 
-- Dumping data for table product
--
-- Table ntstore.product does not contain any data (it is empty)

-- 
-- Dumping data for table export_invoice
--
-- Table ntstore.export_invoice does not contain any data (it is empty)

-- 
-- Dumping data for table import_invoice_product
--
-- Table ntstore.import_invoice_product does not contain any data (it is empty)

-- 
-- Dumping data for table export_invoice_product
--
-- Table ntstore.export_invoice_product does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;